services:
  fonon-bot:
    build: .
    container_name: fonon-bot
    restart: always
    working_dir: /app
    command: ["python", "app/scraper.py"]
    environment:
      - TZ=Asia/Tashkent
    volumes:
      - .:/app
