version: "3.9"

services:
  fonon-bot:
    build: .
    container_name: fonon-bot
    restart: always
    working_dir: /
    command: ["python", "scapper.py"]
    environment:
      - TZ=Asia/Tashkent
    volumes:
      - .:/   # sync host project root with container root
